
input:
  label: f612fb86_c324_4a4b_9162_0292d0937646
  nats:
    auth:
      nkey_file_content: ''
    nak_delay: 1s
    prefetch_count: 524288
    subject: test_topic
    tls:
      skip_cert_verify: true
    urls:
    - nats://nats:4222
output:
  label: ''
  try:
    batching:
      byte_size: 10485760
      count: 1000
      period: 1s
      processors:
      - archive:
          format: concatenate
      - proton_encoding: {}
      - catch:
        - log:
            level: error
            message: 'batching and encoding failed due to: ${!error()}'
        - mapping: deleted()
    catch:
      broker:
        outputs:
        - drop_on:
            back_pressure: ''
            error: true
            output:
              http_client:
                max_in_flight: 1
                max_retry_backoff: ''
                retries: 2
                retry_period: ''
                timeout: 5s
                url: http://localhost:4196/dlq/source-f612fb86-c324-4a4b-9162-0292d0937646
                verb: POST
              processors:
              - mapping: |-
                  root.event = content().string()
                  root.error = @try_error
          label: dlq
        - drop: {}
          label: sink_fails
    outputs:
    - http_client:
        max_in_flight: 10
        max_retry_backoff: 30s
        retries: 300
        retry_period: 1s
        timeout: 10s
        url: http://localhost:3218/proton/v1/ingest/streams/test_stream_raw
        verb: POST
      label: sink
    - drop: {}
      processors:
      - metric:
          name: output_sent_bytes
          type: counter_by
          value: "${! content().length() }"
pipeline:
  processors:
  - label: ''
    mapping: |-
      root = {}
      root.raw = content().string()
  - catch:
    - label: ''
      log:
        fields: {}
        fields_mapping: ''
        level: error
        message: 'processing failed due to: ${!error()}'
    - label: ''
      mapping: deleted()
    label: ''
  threads: -1
