services:
  timeplus:
    image: timeplus/timeplus-enterprise:2.7.0-python-20250210
    ports:
      - 8000:8000
    volumes:
      - timeplus_data:/timeplus/data/
      - ./tp-sync:/timeplus/tp-sync/

volumes:
  timeplus_data:
    driver: local