receivers:
  # Collect logs from Docker containers
  filelog:
    include:
      - /var/lib/docker/containers/*/*.log  # For standard Docker
      - /var/snap/docker/common/var-lib-docker/containers/*/*.log  # For Snap-installed Docker
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      - type: move
        from: attributes.log
        to: body

  # Collect system metrics
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      load: {}

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  resource:
    attributes:
      - key: environment
        value: development
        action: upsert

exporters:
  kafka/logs:
    brokers: ["redpanda:9092"]
    topic: "otel-logs"
    encoding: otlp_json

  kafka/metrics:
    brokers: ["redpanda:9092"]
    topic: "otel-metrics"
    encoding: otlp_json

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [kafka/logs]

    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [kafka/metrics]

    

