receivers:
  # Collect logs from Docker containers
  filelog:
    include:
      - /var/lib/docker/containers/*/*.log  # For standard Docker
      - /var/snap/docker/common/var-lib-docker/containers/*/*.log  # For Snap-installed Docker
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      - type: move
        from: attributes.log
        to: body

exporters:
  kafka:
    brokers: ["redpanda:9092"]
    protocol_version: 2.0.0
    topic: otel-data
    encoding: otlp_json

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [kafka]

