services:
  timeplus:
    image: timeplus/timeplus-enterprise:2.5.4
    container_name: timeplus
    ports:
      - "8000:8000" # Neutron
    environment:
      - MAX_CONCURRENT_QUERIES=100 # Default: 100
      - MAX_CONCURRENT_SELECT_QUERIES=100 # Default: 100
      - MAX_CONCURRENT_INSERT_QUERIES=100 # Default: 100
      - MAX_CONCURRENT_STREAMING_QUERIES=100 # Default: 100
      - MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO=0.95 # Default: 0.9
      - MAX_SERVER_MEMORY_CACHE_TO_RAM_RATIO=0.5 # Default: 0.5
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3218/proton/ping"]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - timeplus_data:/timeplus/data/
      - timeplus_logs:/timeplus/logs/

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

volumes:
  timeplus_data:
    driver: local
  timeplus_logs:
    driver: local
  prom_data:
    driver: local
  grafana_data:
    driver: local