services:
  redpanda:
    image: redpandadata/redpanda:v23.3.4
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
      - --schema-registry-addr 0.0.0.0:8081
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "19092:19092"
      - "9644:9644"  # Admin API
      - "8081:8081"  # Schema Registry
    volumes:
      - redpanda-data:/var/lib/redpanda
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - logging-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - redpanda
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8888:8888"   # Metrics
    networks:
      - logging-network

  vector:
    image: timberio/vector:0.45.0-debian
    container_name: vector
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Required for reading container logs
      - ./vector.toml:/etc/vector/vector.toml
    environment:
      - VECTOR_CONFIG=/etc/vector/vector.toml
    depends_on:
      - otel-collector
    networks:
      - logging-network

  timeplus:
    image: timeplus/timeplus-enterprise:2.7.0
    ports:
      - 8000:8000
      - 8463:8463
    volumes:
      - timeplus_data:/timeplus/data/
    networks:
      - logging-network
  

volumes:
  redpanda-data:
    driver: local
  timeplus_data:
    driver: local

networks:
  logging-network:
    driver: bridge