receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Collect system metrics
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      load: {}

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  kafka/logs:
    brokers: ["redpanda:9092"]
    topic: "otel-logs"
    encoding: otlp_json

  kafka/metrics:
    brokers: ["redpanda:9092"]
    topic: "otel-metrics"
    encoding: otlp_json

service:
  pipelines:
    logs:
      receivers: [otlp]  # Receives logs via OTLP
      processors: [batch]
      exporters: [kafka/logs]

    metrics:
      receivers: [hostmetrics]  # Collects system + OTLP metrics
      processors: [batch]
      exporters: [kafka/metrics]
