receivers:
  # Collect logs from Docker containers
  filelog:
    include:
      - /var/lib/docker/containers/*/*.log
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      - type: add
        field: container_id
        value: attributes.container.id
      - type: add
        field: container_name
        value: attributes.container.name

  # Collect system metrics
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      load: {}

exporters:
  kafka:
    brokers: ["redpanda:9092"]
    protocol_version: 2.0.0
    topic: otel-data
    encoding: json

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [kafka]

    metrics:
      receivers: [hostmetrics]
      exporters: [kafka]
