{
 "title": "Timeplus queries",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queries",
    "label": "Queries",
    "query": {
     "query": "label_values(ProtonQueryInfo_ElapsedMicroseconds,id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running queries",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ProtonMetrics_Query{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Scan EPS",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(ProtonQueryInfo_ScanEvents{}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output EPS",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(ProtonQueryInfo_OutputEvents{}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 queries by scan bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10, rate(ProtonQueryInfo_ScanBytes[1m]))",
       "legendFormat": "{{pod_name}}.{{materialized_view}}"
      }
     ]
    },
    {
     "title": "Top 10 queries by memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10, rate(ProtonQueryInfo_MemoryUsageBytes[1m]))",
       "legendFormat": "{{pod_name}}.{{materialized_view}}"
      }
     ]
    },
    {
     "title": "Top 10 queries by output bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10, rate(ProtonQueryInfo_OutputBytes[1m]))",
       "legendFormat": "{{id}} on {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage by Query",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ProtonQueryInfo_PeakMemoryUsageBytes{id=~\"$queries\"}",
       "legendFormat": "[Peak] {{pod_name}}.{{materialized_view}}"
      },
      {
       "expr": "ProtonQueryInfo_MemoryUsageBytes{id=~\"$queries\"}",
       "legendFormat": "{{pod_name}}.{{materialized_view}}"
      }
     ]
    },
    {
     "title": "Elapsed time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "ProtonQueryInfo_ElapsedMicroseconds{id=~\"$queries\"}",
       "legendFormat": "{{pod_name}}.{{materialized_view}}"
      }
     ]
    },
    {
     "title": "Query scan EPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(ProtonQueryInfo_ScanEvents{id=~\"$queries\"}[1m])",
       "legendFormat": "{{pod_name}}.{{materialized_view}}"
      }
     ]
    },
    {
     "title": "Query output EPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(ProtonQueryInfo_OutputEvents{id=~\"$queries\"}[1m])",
       "legendFormat": "{{pod_name}}.{{materialized_view}}"
      }
     ]
    },
    {
     "title": "Query scan throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ProtonQueryInfo_ScanBytes{id=~\"$queries\"}[1m])",
       "legendFormat": "{{pod_name}}.{{materialized_view}}"
      }
     ]
    },
    {
     "title": "Query output throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ProtonQueryInfo_OutputBytes{id=~\"$queries\"}[1m])",
       "legendFormat": "{{pod_name}}.{{materialized_view}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(ProtonAsyncMetrics_MemoryResident{})"
      }
     ]
    },
    {
     "title": "CPU Ultilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(rate(ProtonProfileEvents_UserTimeMicroseconds{}[1m]) + rate(ProtonProfileEvents_SystemTimeMicroseconds{}[1m]))/1000000",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Network I/O Raft Send",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ProtonProfileEvents_RaftServerSendBytes{}[1m])",
       "legendFormat": "server-send-{{pod_name}}"
      },
      {
       "expr": "sum(rate(ProtonProfileEvents_RaftServerSendBytes{}[1m]))",
       "legendFormat": "sum-server-send"
      },
      {
       "expr": "rate(ProtonProfileEvents_RaftClientSendBytes{}[1m])",
       "legendFormat": "client-send-{{pod_name}}"
      },
      {
       "expr": "sum(rate(ProtonProfileEvents_RaftClientSendBytes{}[1m]))",
       "legendFormat": "sum-client-send"
      }
     ]
    },
    {
     "title": "Network I/O  Raft Receive",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ProtonProfileEvents_RaftServerReceiveBytes{}[1m])",
       "legendFormat": "server-receive-{{pod_name}}"
      },
      {
       "expr": "sum(rate(ProtonProfileEvents_RaftServerReceiveBytes{}[1m]))",
       "legendFormat": "sum-server-receive"
      },
      {
       "expr": "rate(ProtonProfileEvents_RaftClientReceiveBytes{}[1m])",
       "legendFormat": "client-receive-{{pod_name}}"
      },
      {
       "expr": "sum(rate(ProtonProfileEvents_RaftClientReceiveBytes{}[1m]))",
       "legendFormat": "sum-client-receive"
      }
     ]
    },
    {
     "title": "Disk Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by(pod_name)({__name__=~\"ProtonAsyncMetrics_BlockWriteOps.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ProtonAsyncMetrics_MemoryResident{}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "MaterializedView QueryStatus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "ProtonMaterializedView_QueryStatus{}",
       "legendFormat": "{{pod_name}}.{{name}}"
      }
     ]
    },
    {
     "title": "Disk Write throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(pod_name)({__name__=~\"ProtonAsyncMetrics_BlockWriteBytes.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MaterializedView CheckpointDiskUsage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ProtonMaterializedView_CheckpointDiskUsage",
       "legendFormat": "{{pod_name}}.{{name}}"
      }
     ]
    },
    {
     "title": "MaterializedView Query Recovery",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "topk(10, ProtonMaterializedView_QueryRecovery{})",
       "legendFormat": "{{pod_name}}{{name}}"
      }
     ]
    },
    {
     "title": "MaterializedView StorageSize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ProtonMaterializedView_StorageSize",
       "legendFormat": "{{pod_name}}.{{name}}"
      }
     ]
    },
    {
     "title": "MaterializedView CheckpointDiskUsage Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(ProtonMaterializedView_CheckpointDiskUsage)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}