{
 "title": "Timeplus external streams",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values(ProtonExternalStream_ReadBytes,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read - total EPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ProtonExternalStream_ReadRows{name=~\"$stream\"}[1m]))"
    }
   ]
  },
  {
   "title": "Read - total throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ProtonExternalStream_ReadBytes{name=~\"$stream\"}[1m]))"
    }
   ]
  },
  {
   "title": "Write - total EPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ProtonExternalStream_WrittenRows{name=~\"$stream\"}[1m]))"
    }
   ]
  },
  {
   "title": "Write - total throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ProtonExternalStream_WrittenBytes{name=~\"$stream\"}[1m]))"
    }
   ]
  },
  { "title": "By stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Read - throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(ProtonExternalStream_ReadBytes{name=~\"$stream\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write - throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(ProtonExternalStream_WrittenBytes{name=~\"$stream\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Read - failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (name) (rate(ProtonExternalStream_ReadFailed{name=~\"$stream\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write - failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (name) (rate(ProtonExternalStream_WrittenFailed{name=~\"$stream\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}