{
 "title": "Timeplus timeplusd",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queries",
    "label": "Queries",
    "query": {
     "query": "label_values(TimeplusdQueryInfo_ElapsedMicroseconds,id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Queries overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running queries",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(TimeplusdQueryInfo_ElapsedMicroseconds{materialized_view=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running MVs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(TimeplusdQueryInfo_ElapsedMicroseconds{materialized_view!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scan EPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(TimeplusdQueryInfo_ScanEvents{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output EPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(TimeplusdQueryInfo_OutputEvents{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running queries by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "TimeplusdMetrics_Query{}", "legendFormat": "{{pod_name}}" }
   ]
  },
  {
   "title": "Top 10 queries by memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, rate(TimeplusdQueryInfo_MemoryUsageBytes[1m]))",
     "legendFormat": "{{pod_name}}.{{materialized_view}}"
    }
   ]
  },
  {
   "title": "Top 10 queries by scan bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, rate(TimeplusdQueryInfo_ScanBytes[1m]))",
     "legendFormat": "{{pod_name}}.{{materialized_view}}"
    }
   ]
  },
  {
   "title": "Top 10 queries by output bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, rate(TimeplusdQueryInfo_OutputBytes[1m]))",
     "legendFormat": "{{id}} on {{pod_name}}"
    }
   ]
  },
  { "title": "Query details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "TimeplusdQueryInfo_PeakMemoryUsageBytes{id=~\"$queries\"}",
     "legendFormat": "[Peak] {{pod_name}}.{{materialized_view}}"
    },
    {
     "expr": "TimeplusdQueryInfo_MemoryUsageBytes{id=~\"$queries\"}",
     "legendFormat": "{{pod_name}}.{{materialized_view}}"
    }
   ]
  },
  {
   "title": "Elapsed time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "TimeplusdQueryInfo_ElapsedMicroseconds{id=~\"$queries\"}",
     "legendFormat": "{{pod_name}}.{{materialized_view}}"
    }
   ]
  },
  {
   "title": "Query scan EPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(TimeplusdQueryInfo_ScanEvents{id=~\"$queries\"}[1m])",
     "legendFormat": "{{pod_name}}.{{materialized_view}}"
    }
   ]
  },
  {
   "title": "Query output EPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(TimeplusdQueryInfo_OutputEvents{id=~\"$queries\"}[1m])",
     "legendFormat": "{{pod_name}}.{{materialized_view}}"
    }
   ]
  },
  {
   "title": "Query scan throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(TimeplusdQueryInfo_ScanBytes{id=~\"$queries\"}[1m])",
     "legendFormat": "{{pod_name}}.{{materialized_view}}"
    }
   ]
  },
  {
   "title": "Query output throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(TimeplusdQueryInfo_OutputBytes{id=~\"$queries\"}[1m])",
     "legendFormat": "{{pod_name}}.{{materialized_view}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Total Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(TimeplusdAsyncMetrics_MemoryResident{})"
    }
   ]
  },
  {
   "title": "CPU Ultilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(TimeplusdProfileEvents_UserTimeMicroseconds{}[1m]) + rate(TimeplusdProfileEvents_SystemTimeMicroseconds{}[1m]))/1000000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network I/O Raft Send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(TimeplusdProfileEvents_RaftServerSendBytes{}[1m])",
     "legendFormat": "server-send-{{pod_name}}"
    },
    {
     "expr": "sum(rate(TimeplusdProfileEvents_RaftServerSendBytes{}[1m]))",
     "legendFormat": "sum-server-send"
    },
    {
     "expr": "rate(TimeplusdProfileEvents_RaftClientSendBytes{}[1m])",
     "legendFormat": "client-send-{{pod_name}}"
    },
    {
     "expr": "sum(rate(TimeplusdProfileEvents_RaftClientSendBytes{}[1m]))",
     "legendFormat": "sum-client-send"
    }
   ]
  },
  {
   "title": "Network I/O  Raft Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(TimeplusdProfileEvents_RaftServerReceiveBytes{}[1m])",
     "legendFormat": "server-receive-{{pod_name}}"
    },
    {
     "expr": "sum(rate(TimeplusdProfileEvents_RaftServerReceiveBytes{}[1m]))",
     "legendFormat": "sum-server-receive"
    },
    {
     "expr": "rate(TimeplusdProfileEvents_RaftClientReceiveBytes{}[1m])",
     "legendFormat": "client-receive-{{pod_name}}"
    },
    {
     "expr": "sum(rate(TimeplusdProfileEvents_RaftClientReceiveBytes{}[1m]))",
     "legendFormat": "sum-client-receive"
    }
   ]
  },
  {
   "title": "Disk Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by(pod_name)({__name__=~\"TimeplusdAsyncMetrics_BlockWriteOps.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "TimeplusdAsyncMetrics_MemoryResident{}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Timeplusd MaterializedView QueryNode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(TimeplusdMaterializedView_QueryNode{})",
     "legendFormat": "All"
    },
    {
     "expr": "TimeplusdMaterializedView_QueryNode",
     "legendFormat": "{{pod_name}}.{{name}}"
    }
   ]
  },
  {
   "title": "Disk Write throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod_name)({__name__=~\"TimeplusdAsyncMetrics_BlockWriteBytes.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeplusd MaterializedView QueryStatus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "TimeplusdMaterializedView_QueryStatus{}",
     "legendFormat": "{{pod_name}}.{{name}}"
    }
   ]
  },
  {
   "title": "Timeplusd MaterializedView Query Recovery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "topk(10, TimeplusdMaterializedView_QueryRecovery{})",
     "legendFormat": "{{pod_name}}{{name}}"
    }
   ]
  },
  {
   "title": "Timeplusd MaterializedView CheckpointDiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "TimeplusdMaterializedView_CheckpointDiskUsage",
     "legendFormat": "{{pod_name}}.{{name}}"
    }
   ]
  },
  {
   "title": "Timeplusd MaterializedView CheckpointDiskUsage Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(TimeplusdMaterializedView_CheckpointDiskUsage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeplusd MaterializedView StorageSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "TimeplusdMaterializedView_StorageSize",
     "legendFormat": "{{pod_name}}.{{name}}"
    }
   ]
  }
 ]
}