name: timeplus-fraud-detection
services:
  timeplus:
    image: timeplus/timeplus-enterprise:2.5.4
    pull_policy: always
    ports:
      - "8000:8000" # app server http
      - "8463:8463" # timeplusd tcp
      - "3218:3218" # timeplusd http
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:3218/proton/ping" ]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - timeplus_data:/timeplus/data/
      - ./tp-sync:/timeplus/tp-sync/

  fraud-detector: # udf
    image: fraud:830bdae  

  transaction: # transaction simulator
    image: fraud:830bdae
    entrypoint: ["python", "transaction.py"]
    environment:
    - TIMEPLUS_HOST=timeplus

volumes:
  timeplus_data:
    driver: local
