services:
  timeplus:
    image: timeplus/timeplus-enterprise:2.5.11
    environment:
      - ENABLE_AUTHENTICATION=true
      - TIMEPLUSD_CONN_MAX_IDLE_TIME=60
    ports:
      - "8000:8000"
      - "8463:8463"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3218"]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./data:/timeplus/data/

  ddos:
    image: ddos_detection:latest
    container_name: ddos-server
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5001:5001"
