services:
  timeplus:
    image: timeplus/timeplus-enterprise:2.8.1-rc.2
    platform: linux/amd64
    environment:
      - HF_HOME=/root/.cache/huggingface
    ports:
      - "8000:8000"
      - "8463:8463"
      - "8123:8123"
    volumes:
      - timeplus_data:/timeplus/data/
      - hf-cache:/root/.cache/huggingface

  bluebird:
    image: node:latest
    entrypoint: >
      npx @sdairs/bluebird start timeplus --token proton:timeplus@t+ --endpoint http://timeplus:8000/default --stream bluebird
    depends_on:
      - timeplus

  udf:
    image: timeplus/bluesky:39a911d
    ports:
      - "5001:5001"
    environment:
    - BLUESKY_USER=${BLUESKY_USER}
    - BLUESKY_PASSWORD=${BLUESKY_PASSWORD}
    profiles: [development]

  notebook:
    image: jupyter/scipy-notebook:latest
    entrypoint: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    profiles: [development]

volumes:
  timeplus_data:
    driver: local
  hf-cache:
    driver: local